language: php
services: mongodb
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
  - touch src/Graviton/I18nBundle/Resources/translations/i18n.de.odm
php:
  - 5.5
script:
  - true
after_success:
  - "sh deploy.sh"
